# Data Preparation
```{r}
load(file = "./core_data/autodata_clean.Rdata")
```

```{r}
# test and train sets
autodata_purch <- autodata_clean %>% 
  filter(Target == "buy")

autodata_nopurch <- autodata_clean %>% 
  filter(Target != "buy")

#stratified sets

set.seed(85)

autodata_purch_train_ind <- sample(seq_len(nrow(autodata_purch)), floor(nrow(autodata_purch)*0.75),replace = FALSE)
autodata_purch_train <- autodata_purch[autodata_purch_train_ind,]
autodata_purch_test <- autodata_purch[-autodata_purch_train_ind,]

autodata_nopurch_train_ind <- sample(seq_len(nrow(autodata_nopurch)),floor(nrow(autodata_nopurch)*0.75), replace = FALSE)
autodata_nopurch_train <- autodata_nopurch[autodata_nopurch_train_ind,]
autodata_nopurch_test <- autodata_nopurch[-autodata_nopurch_train_ind,]

autodata_train <- rbind(autodata_purch_train, autodata_nopurch_train)
autodata_test <- rbind(autodata_purch_test, autodata_nopurch_test)

#unmodified test & train complete
```

```{r}

#simpler extra parameters

autodata_exparam <- autodata_clean

# total miles
autodata_exparam$totalmil <- autodata_exparam$age_of_vehicle_years * autodata_exparam$annualised_mileage

# loyalty total
autodata_exparam$loyalty <- autodata_exparam$num_serv_dealer_purchased / autodata_exparam$total_services

# reliability
autodata_exparam$reliability <- autodata_exparam$non_sched_serv_warr / autodata_exparam$age_of_vehicle_years

# service cost
autodata_exparam$scost <-  autodata_exparam$total_paid_services / autodata_exparam$total_services

# non-dealer services
autodata_exparam$nondeal <- autodata_exparam$total_services - autodata_exparam$num_serv_dealer_purchased

```

```{r}
# how to create a variable that described car age is between both total miles and age in years, a car can be old because it has high miles or it can be old because it is old in age as a metric

# not linear? age^2? relative wear?

#see below
```

```{r}
# wage https://www.abs.gov.au/ausstats/abs@.nsf/mf/6306.0/
# unused
```

```{r}
# test and train sets wiht extra parameters
autodata_purch <- autodata_exparam %>% 
  filter(Target == "buy")

autodata_nopurch <- autodata_exparam %>% 
  filter(Target != "buy")

#stratified sets

set.seed(85)

autodata_purch_train_ind <- sample(seq_len(nrow(autodata_purch)), floor(nrow(autodata_purch)*0.75),replace = FALSE)
autodata_purch_train <- autodata_purch[autodata_purch_train_ind,]
autodata_purch_test <- autodata_purch[-autodata_purch_train_ind,]

autodata_nopurch_train_ind <- sample(seq_len(nrow(autodata_nopurch)),floor(nrow(autodata_nopurch)*0.75), replace = FALSE)
autodata_nopurch_train <- autodata_nopurch[autodata_nopurch_train_ind,]
autodata_nopurch_test <- autodata_nopurch[-autodata_nopurch_train_ind,]

autodata_exp_train <- rbind(autodata_purch_train, autodata_nopurch_train)
autodata_exp_test <- rbind(autodata_purch_test, autodata_nopurch_test)
```

```{r}
#split extra parameter dataset

autodata_train_nogen <- autodata_exp_train %>% 
  filter(gender == "NULL", age_band != "NULL")

autodata_train_noage <- autodata_exp_train %>% 
  filter(gender != "NULL", age_band == "NULL")

autodata_train_allvar <- autodata_exp_train %>% 
  filter(gender != "NULL", age_band != "NULL")

autodata_train_novar <- autodata_exp_train %>% 
  filter(gender == "NULL", age_band == "NULL")

# train split list
# 89train_exp_split <- llist(autodata_train_nogen, autodata_train_noage, autodata_train_allvar, autodata_train_novar)


# Testing datasets split

autodata_test_nogen <- autodata_exp_test %>% 
  filter(gender == "NULL", age_band != "NULL")

autodata_test_noage <- autodata_exp_test %>% 
  filter(gender != "NULL", age_band == "NULL")

autodata_test_allvar <- autodata_exp_test %>% 
  filter(gender != "NULL", age_band != "NULL")
  
autodata_test_novar <- autodata_exp_test %>% 
  filter(gender == "NULL", age_band == "NULL")

# test split list
# test_exp_split <- llist(autodata_test_nogen, autodata_test_noage, autodata_test_allvar, autodata_test_novar)

```



```{r} 
#list of extra param dataset names
expdata <- c("autodata_exp_train", "autodata_exp_test", "autodata_train_nogen", "autodata_train_noage", "autodata_train_allvar", "autodata_train_novar", "autodata_test_nogen", "autodata_test_noage", "autodata_test_allvar", "autodata_test_novar") 

# age metric (wear) is within set (no leakage) 

for(df in expdata){
 data <- get(df)
 
 #relativ wear
 
  mmil <- mean(data[data$Target == "buy", "totalmil", drop = TRUE])
  mage <- mean(data[data$Target == "buy", "age_of_vehicle_years", drop = TRUE])
  mwear <- mmil* mage
  data$wear <- (data$totalmil * data$age_of_vehicle_years) / mwear
  
# complex reliability based on wear
data$crel <- data$non_sched_serv_warr / data$wear

# maintainence consistency based on wear
data$maincons <- data$wear / data$total_services

# wear till service
data$nextserv <- data$maincons - ((data$wear/data$age_of_vehicle_years/12)*(data$mth_since_last_serv))
  assign(df, data)
}

```

```{r}
#check correlation

auto_cor <- autodata_exp_train %>% 
  select(-ID, -Target, -age_band, -gender, -car_model, -car_segment) %>% 
  cor()
corrplot(auto_cor, method = "number")
```


```{r}
preped_data <- c("autodata_train", "autodata_test")
save(list = preped_data, file = "./core_data/autodata_prep.Rdata")

save(list = expdata, file = "./core_data/extra_param_data.Rdata")
```

```{r}
#wearplot

mmil <- mean(autodata_exp_train[autodata_exp_train$Target == "buy", "totalmil", drop = TRUE])
mage <- mean(autodata_exp_train[autodata_exp_train$Target == "buy", "age_of_vehicle_years", drop = TRUE])
mwear <- mmil*mage

hmmwear <- (autodata_exp_train$totalmil[6856] * autodata_exp_train$age_of_vehicle_years[6856]) / mwear

set.seed(456345)
randomcarindex <- floor(runif(1, 1, 98502))

wearplot <- data.frame(car = c("mean","mean"), age = c(0,mage), miles =c(0,mmil), wear = c(0,mwear), stringsAsFactors = FALSE)
randomorigin <- as.data.frame(cbind(paste("car", randomcarindex, sep ="_"), 0,0,0), stringsAsFactors = FALSE)
randomcar <-cbind(car = paste("car", randomcarindex, sep ="_"), autodata_exp_train[randomcarindex, c(7,18)])
randomcar$wear <- randomcar[,2] * randomcar[,3] 
names(randomcar) <- names(randomorigin)
randomcar <- rbind(randomorigin, randomcar)
names(randomcar) <- names(wearplot)
wearplot <- rbind(wearplot, randomcar)
wearplot$car <- as.factor(wearplot$car)
wearplot$wear <- round(as.numeric(wearplot$wear), digits = 1)
wearplot$age <- as.numeric(wearplot$age)
wearplot$miles <- as.numeric(wearplot$miles)

ggplot(wearplot, aes(x = age, y=miles, group = car, fill = car)) + geom_area() + geom_text(aes(label = wear))

```
